/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CCalendar: typeof import('./../../src/components/c/calendar.vue')['default']
    CTodo: typeof import('./../../src/components/c/todo.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import("element-plus/es")["ElButtonGroup"]
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElConfigProvider: typeof import("element-plus/es")["ElConfigProvider"]
    ElInput: typeof import("element-plus/es")["ElInput"]
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./../../src/components/test.vue')['default']
    YButton: typeof import('./../../src/components/y/button.vue')['default']
    YCalendar: typeof import("./../../src/components/y/calendar.vue")["default"]
    YCell: typeof import('./../../src/components/y/cell.vue')['default']
    YInput: typeof import('./../../src/components/y/input.vue')['default']
    YYLi: typeof import('./../../src/components/y/yLi.vue')['default']
  }
}
